#!/bin/bash

#sed -i "/std::string file_name = /{s/.*/std::string file_name = \"newreno-data\";/}" scratch/long-short3.cc
sed -i 's/TcpCubic/TcpNewReno/' scratch/long-short3.cc

toexec=scratch/long-short3

#for cwnd in 1 2 4 10
for cwnd in 10
do
    for d in "10ms" "50ms" "100ms" "200ms"
    #for d in "2ms" "4ms" "5ms"
    do
        for b in "12Mbps" "100Mbps"
        do
            for que in "20p" "40p" "80p" "160p" "320p" 
            do
                for run in 1
                do
                    queue=$(echo $que | cut -d'p' -f 1)
		    outdir="outNewRenoLS-$cwnd-$d-$b-${queue}_run${run}"
                    echo "$outdir"
                    if [[ ! -f $outdir ]]
                    then
                        mkdir $outdir
                    fi
                    #for pkts in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 40 60 80 100
                    for pkts in 10 20 40 60 80 100 200 400 600 800 1000 2000 4000 6000 8000 10000 
                    do
                        echo "Number of packets: " $pkts
                        #bytes=$( expr 1440 '*' "$pkts")
                        #sed -i "/static const uint32_t totalTxBytes =/{s/.*/static const uint32_t totalTxBytes = $bytes;/}" scratch/long-short3.cc
                        sed -i "/std::string file_name = /{s/.*/std::string file_name = \""${pkts}".newreno-data\";/}" scratch/long-short3.cc
                        sed -i "/uint32_t initcwnd =/{s/.*/uint32_t initcwnd =$cwnd;/}" scratch/long-short3.cc

                        ./waf --run "$toexec --numPkts=$pkts --queueSize=$que --delay=$d --rate=$b" &> $outdir/$pkts.out &
                        #echo "done waf"
                        wait
                        mv *newreno-data* $outdir
                    done
                done
            done
        done
    done
done
sleep 1

pkill -9 -x long-short3


