#!/bin/bash

sed -i "/std::string file_name = /{s/.*/std::string file_name = \"newreno-data\";/}" scratch/fifth-fct.cc
sed -i 's/ns3::TcpCubic/ns3::TcpNewReno/' scratch/fifth-fct.cc

toexec=scratch/fifth-fct

for d in "10ms" "50ms" "100ms" "200ms"
do
    for b in "12Mbps" "100Mbps"
    do
        for que in 20 40 80 160 320
        do
            for run in {1..10}
            do
                outdir="outNewReno-$d-$b-${que}_run${run}"
                echo "$outdir"
                if [[ ! -f $outdir ]]
                then
                    mkdir $outdir
                fi
                for pkts in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 40 60 80 100
                #for pkts in 1 2 
                do
                    echo "Number of packets: " $pkts
                    sed -i "/std::string file_name = /{s/.*/std::string file_name = \""${pkts}".newreno-data\";/}" scratch/fifth-fct.cc

                    ./waf --run "$toexec --numPkts=$pkts --queueSize=$que --delay=$d --rate=$b" &> $outdir/$pkts.out &
                    #echo "done waf"
                    wait
                    mv *newreno-data* $outdir
                done
            done
        done
    done
done
sleep 1

pkill -9 -x fifth-fct

#for f in outNewRenox*/newreno-data-fct-0-0.pcap;
#    do 
#        fct=$(tshark -r "$f" | awk '{print $2, $7, $12}' |  sed 's/\[//' | sed 's/\]//' | sed 's/,//' | sed '/FIN/,$d' | awk 'END {print $1}');
#        num=$(echo "$f" | cut -d'x' -f 2 | cut -d'x' -f 2 | cut -d'/' -f 1);
#        printf "$num  $fct \n" >> newreno-fct-results.tmp;
#done

#cat newreno-fct-results.tmp | sort -n -k1 > newreno-fct-results.txt
#rm newreno-fct-results.tmp
